package com.adiupd123.cookmaster.models

import com.google.gson.annotations.SerializedName

class Recipe(
    @SerializedName("approved_at")val approved_at: Int,
    @SerializedName("aspect_ratio") val aspect_ratio: String,
    @SerializedName("beauty_url")val beauty_url: Any,
    @SerializedName("brand")val brand: Any,
    @SerializedName("brand_id")val brand_id: Any,
    @SerializedName("buzz_id")val buzz_id: Any,
    @SerializedName("canonical_id")val canonical_id: String,
    @SerializedName("compilations")val compilations: List<Any>,
    @SerializedName("cook_time_minutes")val cook_time_minutes: Any,
    @SerializedName("country")val country: String,
    @SerializedName("created_at") val created_at: Int,
    @SerializedName("credits")val credits: List<Credit>,
    @SerializedName("description")val description: String,
    @SerializedName("draft_status")val draft_status: String,
    @SerializedName("facebook_posts")val facebook_posts: List<Any>,
    @SerializedName("id") val id: Int,
    @SerializedName("inspired_by_url")val inspired_by_url: Any,
    @SerializedName("instructions")val instructions: List<Instruction>,
    @SerializedName("is_one_top")val is_one_top: Boolean,
    @SerializedName("is_shoppable")val is_shoppable: Boolean,
    @SerializedName("keywords")val keywords: String,
    @SerializedName("language")val language: String,
    @SerializedName("name") val name: String,
    @SerializedName("num_servings")val num_servings: Int,
    @SerializedName("nutrition")val nutrition: Nutrition,
    @SerializedName("nutrition_visibility")val nutrition_visibility: String,
    @SerializedName("original_video_url")val original_video_url: Any,
    @SerializedName("prep_time_minutes")val prep_time_minutes: Any,
    @SerializedName("price")val price: Price,
    @SerializedName("promotion")val promotion: String,
    @SerializedName("renditions")val renditions: List<Any>,
    @SerializedName("sections")val sections: List<Section>,
    @SerializedName("seo_title")val seo_title: String,
    @SerializedName("servings_noun_plural")val servings_noun_plural: String,
    @SerializedName("servings_noun_singular")val servings_noun_singular: String,
    @SerializedName("show")val show: Show,
    @SerializedName("show_id")val show_id: Int,
    @SerializedName("slug")val slug: String,
    @SerializedName("tags")val tags: List<Tag>,
    @SerializedName("thumbnail_alt_text")val thumbnail_alt_text: String,
    @SerializedName("thumbnail_url") val thumbnail_url: String,
    @SerializedName("tips_and_ratings_enabled")val tips_and_ratings_enabled: Boolean,
    @SerializedName("topics")val topics: List<Topic>,
    @SerializedName("total_time_minutes")val total_time_minutes: Any,
    @SerializedName("total_time_tier")val total_time_tier: Any,
    @SerializedName("updated_at")val updated_at: Int,
    @SerializedName("user_ratings")val user_ratings: UserRatings,
    @SerializedName("video_ad_content")val video_ad_content: Any,
    @SerializedName("video_id")val video_id: Any,
    @SerializedName("video_url")val video_url: Any,
    @SerializedName("yields")val yields: String
)
